SELECT COUNT(1) FROM [Dimension].[City]
SELECT COUNT(1) FROM [Dimension].[Customer]
SELECT COUNT(1) FROM [Dimension].[Date]
SELECT COUNT(1) FROM [Dimension].[Employee]
SELECT COUNT(1) FROM [Dimension].[Payment Method]
SELECT COUNT(1) FROM [Dimension].[Stock Item]
SELECT COUNT(1) FROM [Dimension].[Supplier]
SELECT COUNT(1) FROM [Dimension].[Transaction Type]
SELECT COUNT(1) FROM [Fact].[Movement]
SELECT COUNT(1) FROM [Fact].[Order]
SELECT COUNT(1) FROM [Fact].[Purchase]
SELECT COUNT(1) FROM [Fact].[Sale]
SELECT COUNT(1) FROM [Fact].[Stock Holding]
SELECT COUNT(1) FROM [Fact].[Transaction]
SELECT COUNT(1) FROM [Integration].[City_Staging]
SELECT COUNT(1) FROM [Integration].[Customer_Staging]
SELECT COUNT(1) FROM [Integration].[Employee_Staging]
SELECT COUNT(1) FROM [Integration].[ETL Cutoff]
SELECT COUNT(1) FROM [Integration].[Lineage]
SELECT COUNT(1) FROM [Integration].[Movement_Staging]
SELECT COUNT(1) FROM [Integration].[Order_Staging]
SELECT COUNT(1) FROM [Integration].[PaymentMethod_Staging]
SELECT COUNT(1) FROM [Integration].[Purchase_Staging]
SELECT COUNT(1) FROM [Integration].[Sale_Staging]
SELECT COUNT(1) FROM [Integration].[StockHolding_Staging]
SELECT COUNT(1) FROM [Integration].[StockItem_Staging]
SELECT COUNT(1) FROM [Integration].[Supplier_Staging]
SELECT COUNT(1) FROM [Integration].[Transaction_Staging]
SELECT COUNT(1) FROM [Integration].[TransactionType_Staging]
